name: "CI"

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU binfmt for cross compiling
        uses: docker/setup-qemu-action@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set up binary cache
        uses: cachix/cachix-action@v11
        with:
          name: ephemera
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Check flake
        run: nix flake check

      - name: Run tests
        run: nix develop --command cargo test

  build:
    runs-on: ubuntu-latest
    needs:
      - test

    strategy:
      matrix:
        system:
          - "aarch64-linux"
          - "x86_64-linux"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU binfmt for cross compiling
        uses: docker/setup-qemu-action@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-platforms = aarch64-linux x86_64-linux

      - name: Set up binary cache
        uses: cachix/cachix-action@v11
        with:
          name: ephemera
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build package
        run: nix build .#packages.${{ matrix.system }}.default
