name: update-flake-inputs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install Nix
        uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v23
        with:
          pr-title: "update flake inputs"
          pr-labels: |
            update
            automated
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
